import { Product } from '@/types/product';

export const dummyProducts: Product[] = [
  {
    id: 1,
    name: 'iPhone 14 Pro Max 256GB',
    slug: 'iphone-14-pro-max-256gb',
    permalink: '/product/iphone-14-pro-max-256gb',
    date_created: '2024-01-01',
    date_modified: '2024-01-01',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: '<p>Experience the ultimate iPhone with the stunning 6.7-inch Super Retina XDR display.</p>',
    short_description: 'Latest iPhone with A16 Bionic chip',
    sku: 'IPH14PM256',
    price: '850000',
    regular_price: '950000',
    sale_price: '850000',
    date_on_sale_from: null,
    date_on_sale_to: null,
    price_html: '',
    on_sale: true,
    purchasable: true,
    total_sales: 156,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 25,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '240g',
    dimensions: { length: '160.7', width: '77.6', height: '7.85' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.8',
    rating_count: 245,
    related_ids: [2, 3],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 1, name: 'Phones', slug: 'phones' }],
    tags: [{ id: 1, name: 'flash-sale', slug: 'flash-sale' }, { id: 2, name: 'deal', slug: 'deal' }],
    images: [
      {
        id: 1,
        src: 'https://images.unsplash.com/photo-1678652197831-2d180705cd2c?w=500',
        name: 'iPhone 14 Pro Max',
        alt: 'iPhone 14 Pro Max',
        date_created: '2024-01-01',
        date_modified: '2024-01-01',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
    store: {
      id: 1,
      name: 'Apple Official Store',
      shop_name: 'Apple Store',
      url: '/vendor/apple-store',
      address: {},
    },
  },
  {
    id: 2,
    name: 'Samsung Galaxy S23 Ultra',
    slug: 'samsung-galaxy-s23-ultra',
    permalink: '/product/samsung-galaxy-s23-ultra',
    date_created: '2024-01-01',
    date_modified: '2024-01-01',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: '<p>The ultimate S series with a built-in S Pen and the highest resolution camera on a phone.</p>',
    short_description: 'Flagship Samsung phone with S Pen',
    sku: 'SAMS23U',
    price: '720000',
    regular_price: '850000',
    sale_price: '720000',
    date_on_sale_from: null,
    date_on_sale_to: null,
    price_html: '',
    on_sale: true,
    purchasable: true,
    total_sales: 198,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 35,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '234g',
    dimensions: { length: '163.4', width: '78.1', height: '8.9' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.7',
    rating_count: 312,
    related_ids: [1, 3],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 1, name: 'Phones', slug: 'phones' }],
    tags: [{ id: 1, name: 'flash-sale', slug: 'flash-sale' }],
    images: [
      {
        id: 2,
        src: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500',
        name: 'Samsung Galaxy S23 Ultra',
        alt: 'Samsung Galaxy S23 Ultra',
        date_created: '2024-01-01',
        date_modified: '2024-01-01',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
    store: {
      id: 2,
      name: 'Samsung Official Store',
      shop_name: 'Samsung Store',
      url: '/vendor/samsung-store',
      address: {},
    },
  },
  {
    id: 3,
    name: 'Sony WH-1000XM5 Headphones',
    slug: 'sony-wh-1000xm5-headphones',
    permalink: '/product/sony-wh-1000xm5-headphones',
    date_created: '2024-01-01',
    date_modified: '2024-01-01',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: '<p>Industry-leading noise cancellation with premium sound quality.</p>',
    short_description: 'Premium noise-cancelling headphones',
    sku: 'SONYWH1000XM5',
    price: '185000',
    regular_price: '220000',
    sale_price: '185000',
    date_on_sale_from: null,
    date_on_sale_to: null,
    price_html: '',
    on_sale: true,
    purchasable: true,
    total_sales: 432,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 50,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '250g',
    dimensions: { length: '20', width: '18', height: '9' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.9',
    rating_count: 567,
    related_ids: [4, 5],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 2, name: 'Electronics', slug: 'electronics' }],
    tags: [{ id: 2, name: 'deal', slug: 'deal' }],
    images: [
      {
        id: 3,
        src: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500',
        name: 'Sony Headphones',
        alt: 'Sony WH-1000XM5',
        date_created: '2024-01-01',
        date_modified: '2024-01-01',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
  },
  {
    id: 4,
    name: 'MacBook Pro 14" M2',
    slug: 'macbook-pro-14-m2',
    permalink: '/product/macbook-pro-14-m2',
    date_created: '2024-01-01',
    date_modified: '2024-01-01',
    type: 'simple',
    status: 'publish',
    featured: true,
    catalog_visibility: 'visible',
    description: '<p>Supercharged by M2 Pro or M2 Max chip with up to 96GB unified memory.</p>',
    short_description: 'Pro laptop with M2 chip',
    sku: 'MBP14M2',
    price: '1250000',
    regular_price: '1450000',
    sale_price: '1250000',
    date_on_sale_from: null,
    date_on_sale_to: null,
    price_html: '',
    on_sale: true,
    purchasable: true,
    total_sales: 87,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 15,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '1600g',
    dimensions: { length: '31.26', width: '22.12', height: '1.55' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.9',
    rating_count: 178,
    related_ids: [1, 5],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 3, name: 'Computers', slug: 'computers' }],
    tags: [{ id: 1, name: 'flash-sale', slug: 'flash-sale' }],
    images: [
      {
        id: 4,
        src: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
        name: 'MacBook Pro',
        alt: 'MacBook Pro 14 inch',
        date_created: '2024-01-01',
        date_modified: '2024-01-01',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
  },
  {
    id: 5,
    name: 'Nike Air Max 270',
    slug: 'nike-air-max-270',
    permalink: '/product/nike-air-max-270',
    date_created: '2024-01-01',
    date_modified: '2024-01-01',
    type: 'simple',
    status: 'publish',
    featured: false,
    catalog_visibility: 'visible',
    description: '<p>Iconic sneakers with the tallest Air unit yet for all-day comfort.</p>',
    short_description: 'Comfortable lifestyle sneakers',
    sku: 'NIKEAM270',
    price: '95000',
    regular_price: '120000',
    sale_price: '95000',
    date_on_sale_from: null,
    date_on_sale_to: null,
    price_html: '',
    on_sale: true,
    purchasable: true,
    total_sales: 623,
    virtual: false,
    downloadable: false,
    external_url: '',
    button_text: '',
    tax_status: 'taxable',
    tax_class: '',
    manage_stock: true,
    stock_quantity: 120,
    stock_status: 'instock',
    backorders: 'no',
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: '450g',
    dimensions: { length: '30', width: '12', height: '10' },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: '',
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: '4.6',
    rating_count: 892,
    related_ids: [],
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: '',
    categories: [{ id: 4, name: 'Fashion', slug: 'fashion' }],
    tags: [{ id: 2, name: 'deal', slug: 'deal' }],
    images: [
      {
        id: 5,
        src: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
        name: 'Nike Sneakers',
        alt: 'Nike Air Max 270',
        date_created: '2024-01-01',
        date_modified: '2024-01-01',
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    meta_data: [],
  },
];

// Filter products by tag
export const getProductsByTag = (tag: string): Product[] => {
  return dummyProducts.filter((product) =>
    product.tags.some((t) => t.slug === tag)
  );
};

// Get featured products
export const getFeaturedProducts = (): Product[] => {
  return dummyProducts.filter((product) => product.featured);
};

// Get products by category
export const getProductsByCategory = (categorySlug: string): Product[] => {
  return dummyProducts.filter((product) =>
    product.categories.some((cat) => cat.slug === categorySlug)
  );
};